<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO3xXTq4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO3xXTq4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO3xXTq4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO3xXTq4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO3xXTq4\App_KernelDevDebugContainer([
    'container.build_hash' => 'O3xXTq4',
    'container.build_id' => '1218eca3',
    'container.build_time' => 1631191228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO3xXTq4');
